name: ğŸµ Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ğŸŒ³ Checkout
      uses: actions/checkout@v4

    # - name: ğŸ”¦ Set up Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: '3.3' # Not needed with a .ruby-version file
    #     bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    
    # use bash to run the following commands
    - name: ğŸ§± Build the site
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && bundle install && bundle exec jekyll build --future"

    - name: ğŸ“¦ GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@3.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: ourfor@qq.com
        jekyll: no
        commit_message: ğŸ“ update site
                